---
kind: pipeline
type: vm
name: build and publish binaries

node:
  cluster: mac1

pool:
  use: osx-anka

steps:
  - name: build linux binary
    image: golang:1
    commands:
      - CGO_ENABLED=1 go build -ldflags "-extldflags \"-static\"" -o drone-runner-aws-linux-amd64
    depends_on:
      - clone
  - name: build mac intel binary
    commands:
      - brew install golang
      - CGO_ENABLED=1 go build  -o drone-runner-aws-darwin-amd64
      - ./drone-runner-aws-darwin-amd64 --help
    depends_on:
      - clone
