kind: pipeline
type: vm
name: default

pool:
  use: ubuntu

steps:
  - name: check install
    commands:
      - cat /var/log/cloud-init-output.log
  - name: build binary with golang image
    image: golang:1.16
    commands:
      - GOPATH="" CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o release/linux/amd64/drone-runner-aws
  - name: plugin
    image: plugins/docker
    settings:
      dry_run: true
      repo: foo/bar
      tags: latest
      dockerfile: docker/Dockerfile.linux.amd64
    volumes:
      - name: cache
        path: /go
  - name: docker status
    commands:
      - docker ps -a
  - name: ping
    image: redis
    commands:
      - redis-cli -h red ping

services:
  - name: red
    image: redis

volumes:
  - name: cache
    temp: {}